# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: pretty-format-json
        args: [ --autofix ]
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
